language: python

python:
- 3.6

env:
  global:
  - TMDB_LIST_ID=96926
  - secure: Yw4R+6x1QecQJ8ZFqx5L6GilM37yWyMrcS7LeUhbVrCO8YKsVfLO1B8AZSRiCLd9rqbxERC2HQwjja6Cuokk0SfS75r2KvstNblA1k2LlxRv3ECEfzWTr127BoFrL3iAAYIY06HGNwJ8HtnLW/ThZ9Eovu1gTpMCMzRgmEuI6z3X+4KDHxD8lcrORKFXRoOv8xkc8zi+jva2o6+TWKpNQkkzOxRNAp6PVrdOi40Km4xcJJuhAD4dX4Tm5ZDghLPtwE3cIqrDbHxqLtGl/LaKqCXDSWhFr1FhJbPxLhsvRLs8qJs1FhNgwHbTrroImyoH6FNM07mQQKjg5Ijvk1qcrjWdaAmvOkwksS7ze1rsyYFX5WVQPXzKA/j/sH880B7OsuE60E3yQlD5a2uIdZohz79T59bO9u/sAzqkPrbEFI06bC215HUS6P9jCtKq0XrPKntiIoASENRvzBrWAF3mAGwjzgOV998N73wsU+wb6tj3yelTfjPeV1aN6+eHGl9i7HsebynkkIkqAw83ddQLva3lDhY9lp7wT+QYreyIV1HNNAutdC1v4KmwTL27Q4gJCryo08WniXXXj4irPVJrijIZa/euLINehrLCx5IS5Yp20CNdrahZ2VO4GiO63CGHJyWJSZm+32Jyyy1byIaz2HRlCFPXAHLEJ7pEU4A8lxo=
  - secure: pb6uFrv8XdVRzIvKVr9Cuj+sxh4/iamD/sKV+jz9ZjIhhl88IfRfNbYoIgGhIcjs2Rgrsv6e00+wni1El6TaFktH9Bb1sV64qx6gnIs8/Nzt31F7+oVfp8kMBtut6utEJRnXdZnBbmozprhYnq9qmhqxWSLQR9+pEE2Tw2SodT94vvaLyqZqVUKIQ0QABdnQ0A0f8YdJmRgEIKIPENpSz+jAzywADg6pE6xKO4X+Ls0HDtLbyZXhcWLstnrYXw7RQCQ0YSAw5Db5h358BeGS+31YpsYvcvcx7h5V+zgJiY0WYViDzPDKlNFFYM659YHFRBIrtuExZHGtlhZat5GsBXVlhiE9ZF1WEVFr4/Mt+/rAwJtRu9X2iByonk3wQ3cxcVg29VHB/n/tGaCF7Frw8PjOiWuesY5HFhwOe92VDb1KzkTmJ0o257eSk0W2G+Ql5Xmv0ZHT6D/HW54agDuxpKlRFoeLuqqe6509QPBkKWBBT9G1pK3FMmsNK6u2OmFCjvVt9mLGwlkWWf2D2OxeXmrB8G4QwcgkUMEiLErU3SqEb06nibmlUeLOfVNoZC3yotuWgy9XgvlAW6R6RPnSY8we+oncheR10+wFvKsvbLvmWAswkzbfcfSe5zubKRcYVNdsSemrvoSF2CUuYfEaI63HfFmlWKi1VWYp3dDDpcY=
  - secure: X46nUdyIo18p1uyWh2SfOhuGo7Vg+Ep6yrgbFXFgc7vvYyLC4gLQuL9gi+EOV1yxtKUSf0+lBcMHrB9kjesq/o+j4qeHBD9h5qBrSDSfam8Ws+vGHMPvtuHZz9vVwfoBdHZjgzcoAfTE0+/rlx6zFl4+PTNiySF4SpgAHrgcj35Lf5JEuqCk4Uie2pLoYd42VlDz2vdqzzUPlIOZqvMHhWm9eFUqp2Mtuc9LAgOZCfPgQqTeroJX/XQQvx8BzkAQlZtRhwEBdcBMsqzeHVWIsDD9Z/dnxA3VhHjUvobQkIx3T602MpFR2yq6lJr7eBOZDuSVPnJ2+20YzsW4cIhq3IhfB+Te7gpHaY5OhaBrMZicJlTtnOXCclDwMM7La0xHSvTSuXr85GN53Pz1NVNs8NRYTndgOE0aYPVXWT/GTgAkjPWNNkFKiW//QAhmaVGhp9/ekY8W6vxsoBrnRPkIZXChF2lEVCHoSF4oWH8h8XpMh0i13pEcqGYUiWx3BlStMqmXuZdn2+yE4FhuvmQ7n3YZStRI6RFwW0Mioy78Ltx+79xG/bi2fbyFQjkLhJ0AwX1ihUPN/qI26WCnwLAOdPRV67xuYEqLc1ObX6uwwj+GpO7tSZgf4ploU8O/HrkrgV+E42SQdUQkS6m+QiZ3ig/F3UuRmSsn2ScfZrmWlMo=
  - secure: AFsF2pOIs6FKfxd1pwkTVDNpac7f5NnAy9D8gvxwZgWxSVeT3LtpE1RRkhSc9ZkUU6JheYKUE0SQn1WCYrFlWvdhpR7eNCAZpf5tT5P9mYDpElH7/G3fgXQQ71drayqO9d9QBNU47MgOje+Wf2in09+3gQdB/UhRVwIc+oOLIAcpmvKuvm6/bk5SjZMqMyCEHdIDiO1P912zVArB1DZFqfL9+dRf1ef8vUHjmcuu5HoHMvLaJMGjVCV3o+T+9ES2AqCF5KZIPkozqLIYdPXqqA+skr8vvjHaZjjEQn7oNcKiKYLbtCPZ+Ax+dFtw+Cg8/xu2KouHIzPbQKlgC3t6Dv4B6ZvmZCvbka/2lOztqenBabEbyIl/iPV1ukUs0C+LjZXY0q9GkfapGo11dqIX24xaIeSZYoR4UrPOsGEhCvn7utDKs23fHFybSm3C67B4Aj7PTbhrNQ2RYU/Oh+l2X64R1sjynxSIss8LSjFjB9BMt44JswE07AwN19U34LRFVN9a3DOGRZiCabUjr5+vOgxpi8/EYESh6Ee+TW1TuDSmJjlHYv9KCcxgJ7Iz73bXck6gsdjXT+tMRv0gecNzUBImGOliAQeyjG3TrhXRAau6YeRAeJ99Q3ufgbrQqQqdyxXBXHceRnxffsqhz18LFOlP8be1mAhc6T3PalxfDSI=
  - secure: ZUHS9nPfFsLyTMih0SPNM836XzNbhKUzaTgKFegsKBBi/NkcktOE7buWmOlhN7GtwOcUavQaQVjSApE2Vd9ki3CKAOTbmDsaEIXb+SuaXCkGKz9uUfop+oXEPQaiAW6gXK1sOkIRYyptBAWSxxVvDg8DPAn8iQ0bM+cYgOMDXQTaXWo1kq82aZzF7er4MguCuL/EwzGXfl2aoM5KKBBr/KuLZXPOrKcYCVHpwR6y0mmXszsZi4OusbzgTeRPzyl0U+F/65BV47uDrRJL3RBPz3S1fQK1qxw06Dx0Op7gx4cxivtROlQ/vcfrvqs7wz9orOGJmZLpVbKsIHubuwSqLVquNbAFoD8vXNIKaioJQ1VQPvw2gR+3CNjCsjR2HzFYEHtu4WtR6kPLS9gEiPLHvIFu/ldwCfkLtm5Aa0Oom1qt2e3u/GxeOOs7RMGuvvmxEMP0K7n7Remo4HDaa10uFAmNXILr2RX7/EwjXehzjlAz1mEWdtgZkYq0mUwnw7cKsdNY5CMBsnC4FRSfrrlHYTAXTDtQcZOiYo17APa/RI77f/xbPM6TXZPlXsnPtQUsV82NrJO3JFtuODpf9cN8X2RJOH378QxafYG0iyZq3ngs8xPrvTcgNbQWoipAuVXnKEqMa/uGlgXrabqKoGR3jhkB9Ky8H0r6I2eZL8CvAQY=

cache:
  pip: true
  directories:
  - "$HOME/.cache/pypoetry"

install:
- curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py
  | python
- source $HOME/.poetry/env
- poetry install
- poetry build

script:
- black --check isle/ tests/
- pytest --exitfirst tests/

deploy:
  on:
    tags: true
  provider: script
  skip_cleanup: true
  script: poetry publish -u $PYPI_USERNAME -p $PYPI_PASSWORD
